export enum GameStatus {
    WAITING_FOR_PLAYERS_TO_JOIN = 'WAITING_FOR_PLAYERS_TO_JOIN',
    WAITING_FOR_PLAYERS_TO_ADD_FOOD = 'WAITING_FOR_PLAYERS_TO_ADD_FOOD',
    WAITING_FOR_PLAYERS_TO_FINISH_EVOLVING = 'WAITING_FOR_PLAYERS_TO_FINISH_EVOLVING',
    WAITING_FOR_PLAYERS_TO_FEED = 'WAITING_FOR_PLAYERS_TO_FEED',
    ADDING_FOOD_TO_WATER_PLAN = 'ADDING_FOOD_TO_WATER_PLAN',
    CHOOSING_EVOLVING_ACTION = 'CHOOSING_EVOLVING_ACTION',
    FEEDING_SPECIES = 'FEEDING_SPECIES',
}
