import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { dir } from 'i18next'
import { languages } from '@/src/i18n/settings'

export async function generateStaticParams() {
    return languages.map((lng) => ({ lng }))
}

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({ children, params }: { children: React.ReactNode; params: { lang: string } }) {
    return (
        <html lang={params.lang} dir={dir(params.lang)}>
            <body className={inter.className}>{children}</body>
        </html>
    )
}
